name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: aa900031/github-actions/setup-node@main
        with:
          no-turbo-cache: 'true'

      - name: Test configs
        run: pnpm test
